package com.Product.Backlog.entity;

import java.util.Date;
import java.util.List;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToMany;
import javax.persistence.Table;

@Entity  //JPA entity mapped to database table 
@Table(name = "Epic")  //table name entity is mapped to 
public class Epic {
	@Id    //primary key of epic
	@GeneratedValue(strategy = GenerationType.AUTO)// value for attribute is automatically generated by db 
	@Column(name = "id")
	Integer id;
	Integer projectCode;
	Integer sprintID;
	String name;
	Date createdOn;
	Date completedOn;
	String status;

	@OneToMany(cascade = CascadeType.ALL) //Epic have multiple user story instances associated with
	//CascadeType.ALL any changes in epic instance is propagated to all associated User story ins
	@JoinColumn(name = "epic_id", referencedColumnName = "id", insertable = false, updatable = false)
	private List<UserStory> userStory;

	public Epic() { //constructor for initializing the attributes 
	}
	
	public Epic(Integer projectCode, Integer sprintID, String name, Date createdOn, Date completedOn, String status) {
		super();
		this.projectCode = projectCode;
		this.sprintID = sprintID;
		this.name = name;
		this.createdOn = createdOn;
		this.completedOn = completedOn;
		this.status = status;
	}
    //getter and setter for attributes 
	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getProjectCode() {
		return projectCode;
	}

	public void setProjectCode(Integer projectCode) {
		this.projectCode = projectCode;
	}

	public Integer getSprintID() {
		return sprintID;
	}

	public void setSprintID(Integer sprintID) {
		this.sprintID = sprintID;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Date getCreatedOn() {
		return createdOn;
	}

	public void setCreatedOn(Date createdOn) {
		this.createdOn = createdOn;
	}

	public Date getCompletedOn() {
		return completedOn;
	}

	public void setCompletedOn(Date completedOn) {
		this.completedOn = completedOn;
	}

	public String getStatus() {
		return status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public List<UserStory> getUserStory() {
		return userStory;
	}

	public void setUserStory(List<UserStory> userStory) {
		this.userStory = userStory;
	}

	@Override
	public String toString() {
		return "Epic [id=" + id + ", projectCode=" + projectCode + ", sprintID=" + sprintID + ", name=" + name
				+ ", createdOn=" + createdOn + ", completedOn=" + completedOn + ", status=" + status + "]";
	}

}